Jshoolsguild 8 prepare main structure
IntiveJsHooligans/memorable pull request #4
Opened 2018-02-05 21:05 UTC by parfienczyk

2018-02-05 21:06 UTC, parfienczyk commented
![screen shot 2018-02-05 at 22 04 41](https://user-images.githubusercontent.com/1235773/35828679-bdb64eba-0ac0-11e8-901b-527d79ffa36f.png)


Example of structure ^^

2018-02-06 11:43 UTC, mareksupruniuk requested changes

2018-02-06 11:43 UTC, MarekSupruniukIntive commented on src/app/app.component.html
> +    <h2>
you shouldn't use `<h2 />` tag here, pick `<h3 />` or skip such element at all since it creates invalid document outline

2018-02-06 12:32 UTC, mareksupruniuk approved these changes

2018-02-06 18:17 UTC, mariuszkalinski approved these changes

2018-02-06 23:03 UTC, patrykkarny reviewed
Squash your commits before merge, check [here](https://git-scm.com/book/id/v2/Git-Tools-Rewriting-History) how to do it ;)

2018-02-06 23:03 UTC, patrykkarny commented on src/app/features/auth/auth.module.ts
> +const routes: Routes = [
consider to move this routes into separate `child-routing.module`, each feature module should have their own separate `routing`, check in the docs how to do it [https://angular.io/guide/router#hero-feature-route-configuration](url)

2018-02-06 23:03 UTC, patrykkarny commented on src/app/features/todos/todos.module.ts
> +const routes: Routes = [
move this routes into separate `child-routing.module`

2018-02-07 07:21 UTC, dkwasniewski approved these changes

2018-02-08 06:25 UTC, merged